
package com.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.5
 * Fri Apr 14 16:24:22 CEST 2023
 * Generated source version: 3.5.5
 */

@XmlRootElement(name = "getAllPoliticians", namespace = "http://www.wsPolitician.com")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAllPoliticians", namespace = "http://www.wsPolitician.com")

public class GetAllPoliticians {


}

