
package com.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.5
 * Fri Apr 14 16:24:21 CEST 2023
 * Generated source version: 3.5.5
 */

@XmlRootElement(name = "getPolitician", namespace = "http://www.wsPolitician.com")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getPolitician", namespace = "http://www.wsPolitician.com")

public class GetPolitician {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

