
package com.wspolitician.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-04-14T16:26:09.947+02:00
 * Generated source version: 3.5.5
 *
 */
public final class PoliticianServiceImp_PoliticianServiceImpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.wsPolitician.com", "PoliticianServiceImpService");

    private PoliticianServiceImp_PoliticianServiceImpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PoliticianServiceImpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PoliticianServiceImpService ss = new PoliticianServiceImpService(wsdlURL, SERVICE_NAME);
        PoliticianServiceImp port = ss.getPoliticianServiceImpPort();
        
        {
        System.out.println("Invoking addPolitician...");
        com.wspolitician.client.Politician _addPolitician_arg0 = new com.wspolitician.client.Politician();
        _addPolitician_arg0.setDeptName("Val d'Oise");
        _addPolitician_arg0.setDeptNumber("95");
        _addPolitician_arg0.setFirstName("Isabel");
        _addPolitician_arg0.setId(0);
        _addPolitician_arg0.setJob("Député");
        _addPolitician_arg0.setLastName("Beressi");
        _addPolitician_arg0.setPartyId("12");
        _addPolitician_arg0.setSex("F");
        _addPolitician_arg0.setTwitterId("683705719");
        
        boolean _addPolitician__return = port.addPolitician(_addPolitician_arg0);
        System.out.println("addPolitician.result=" + _addPolitician__return);
        System.out.println(_addPolitician_arg0.getLastName()+" has been added succesfully");


        }
        
        {
        System.out.println("Invoking addPolitician...");
        com.wspolitician.client.Politician _addPolitician_arg0 = new com.wspolitician.client.Politician();
        _addPolitician_arg0.setDeptName("Meurthe-et-Moselle");
        _addPolitician_arg0.setDeptNumber("54");
        _addPolitician_arg0.setFirstName("Thibault");
        _addPolitician_arg0.setId(1);
        _addPolitician_arg0.setJob("Député");
        _addPolitician_arg0.setLastName("Bazin");
        _addPolitician_arg0.setPartyId("4");
        _addPolitician_arg0.setSex("H");
        _addPolitician_arg0.setTwitterId("783705719");
        boolean _addPolitician__return = port.addPolitician(_addPolitician_arg0);
        System.out.println("addPolitician.result=" + _addPolitician__return);
        System.out.println(_addPolitician_arg0.getLastName()+" has been added succesfully");

        }

        {
        System.out.println("Invoking deletePolitician...");
        int _deletePolitician_arg0 = -1806773430;
        boolean _deletePolitician__return = port.deletePolitician(_deletePolitician_arg0);
        System.out.println("deletePolitician.result=" + _deletePolitician__return);
        if(_deletePolitician__return == false) {
        	System.out.println("The politicien doesn't exist or couldn't have been deleted");
        }
        else {
        	System.out.println("The politicien has been deleted succesfully");
        }

        }
        {
        System.out.println("Invoking getAllPoliticians...");
        java.util.List<com.wspolitician.client.Politician> _getAllPoliticians__return = port.getAllPoliticians();
        System.out.println("getAllPoliticians.result=" + _getAllPoliticians__return);


        }
        {
        System.out.println("Invoking getPoliticianParti...");
        int _getPoliticianParti_arg0 = 1;
        java.lang.String _getPoliticianParti__return = port.getPoliticianParti(_getPoliticianParti_arg0);
        System.out.println("getPoliticianParti.result=" + _getPoliticianParti__return);


        }

        {
        System.out.println("Invoking getPolitician...");
        int _getPolitician_arg0 = 0;
        com.wspolitician.client.Politician _getPolitician__return = port.getPolitician(_getPolitician_arg0);
        System.out.println("getPolitician.result=" + _getPolitician__return);


        }

        System.exit(0);
    }

}
