
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.wspolitician.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-04-14T16:26:09.987+02:00
 * Generated source version: 3.5.5
 *
 */

@javax.jws.WebService(
                      serviceName = "PoliticianServiceImpService",
                      portName = "PoliticianServiceImpPort",
                      targetNamespace = "http://www.wsPolitician.com",
                      wsdlLocation = "file:/C:/Users/evafl/Politicians-soap-ws-fonctionnel/Politicians-soap-ws/src/main/webapp/wsdl/politicianserviceimp.wsdl",
                      endpointInterface = "com.wspolitician.client.PoliticianServiceImp")

public class PoliticianServiceImpPortImpl implements PoliticianServiceImp {

    private static final Logger LOG = Logger.getLogger(PoliticianServiceImpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wspolitician.client.PoliticianServiceImp#deletePolitician(int arg0)*
     */
    public boolean deletePolitician(int arg0) {
        LOG.info("Executing operation deletePolitician");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.wspolitician.client.PoliticianServiceImp#getAllPoliticians()*
     */
    public java.util.List<com.wspolitician.client.Politician> getAllPoliticians() {
        LOG.info("Executing operation getAllPoliticians");
        try {
            java.util.List<com.wspolitician.client.Politician> _return = new java.util.ArrayList<com.wspolitician.client.Politician>();
            com.wspolitician.client.Politician _returnVal1 = new com.wspolitician.client.Politician();
            _returnVal1.setDeptName("DeptName324631582");
            _returnVal1.setDeptNumber("DeptNumber291462902");
            _returnVal1.setFirstName("FirstName642047398");
            _returnVal1.setId(-1739470337);
            _returnVal1.setJob("Job-206773333");
            _returnVal1.setLastName("LastName536172745");
            _returnVal1.setPartyId("PartyId1532428796");
            _returnVal1.setSex("Sex-4454264");
            _returnVal1.setTwitterId("TwitterId-1358495039");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.wspolitician.client.PoliticianServiceImp#getPoliticianParti(int arg0)*
     */
    public java.lang.String getPoliticianParti(int arg0) {
        LOG.info("Executing operation getPoliticianParti");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return1294736354";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.wspolitician.client.PoliticianServiceImp#addPolitician(com.wspolitician.client.Politician arg0)*
     */
    public boolean addPolitician(com.wspolitician.client.Politician arg0) {
        LOG.info("Executing operation addPolitician");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.wspolitician.client.PoliticianServiceImp#getPolitician(int arg0)*
     */
    public com.wspolitician.client.Politician getPolitician(int arg0) {
        LOG.info("Executing operation getPolitician");
        System.out.println(arg0);
        try {
            com.wspolitician.client.Politician _return = new com.wspolitician.client.Politician();
            _return.setDeptName("DeptName1086873122");
            _return.setDeptNumber("DeptNumber-1952758347");
            _return.setFirstName("FirstName246388844");
            _return.setId(1366630513);
            _return.setJob("Job-776760492");
            _return.setLastName("LastName-1535695569");
            _return.setPartyId("PartyId810862985");
            _return.setSex("Sex-1447043189");
            _return.setTwitterId("TwitterId-1982503809");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
